[package]
name = "dft_types"
version = "0.4.0"
edition = "2018"

[dependencies] 
ic-cdk = "0.4.0"
hex = {version = "0.4.3", features = ["serde"] }
crc32fast = "1.3.2"
candid = "0.7.10"
serde = "1.0.135"
serde_bytes = "0.11"
sha2 = "0.10.2"
anyhow = "1.0.56"
thiserror = "1.0"