[package]
name = "dft_standard"
version = "0.1.0"
edition = "2018"

[dependencies] 
ic-cdk = "0.3.3"
ic-cdk-macros = "0.3.3"
dft_types = { path = "../dft_types" }
dft_utils = { path = "../dft_utils" }
candid = "0.7.10"
serde = "1.0.134"
serde_bytes = "0.11"

[dev-dependencies]
rstest = "0.12.0"