[package]
name = "dft_standard"
version = "0.1.0"
edition = "2018"

[dependencies] 
dft_types = { path = "../dft_types" }
dft_utils = { path = "../dft_utils" }
ic-cdk = "0.3.3"
candid = "0.7.10"
serde = "1.0.133"
serde_bytes = "0.11"

[dev-dependencies]
base64 = "0.13.0"
rstest = "0.12.0"