[package]
name = "dft_utils"
version = "0.1.0"
edition = "2018"

[dependencies] 
hex = {version = "0.4.2", features = ["serde"] }
candid = "0.7.4"
serde = "1.0.127"
num-bigint = "0.4.2"
crc32fast = "1.2.0"
base32 = "0.4.0"