[package]
name = "dft_utils"
version = "0.1.0"
edition = "2018"

[dependencies] 
hex = {version = "0.4.3", features = ["serde"] }
candid = "0.7.10"
serde = "1.0.133"
num-bigint = "0.4.3"
crc32fast = "1.3.0"
base32 = "0.4.0"