[package]
name = "dft_types"
version = "0.1.4"
edition = "2018"

[dependencies] 
ic-cdk = "0.3.3"
hex = {version = "0.4.3", features = ["serde"] }
crc32fast = "1.3.1"
candid = "0.7.10"
serde = "1.0.133"
serde_bytes = "0.11"
sha2 = "0.10.1"
anyhow = "1.0.53"
thiserror = "1.0"