[workspace]
members = [
    "dft_basic",
    "dft_burnable",
    "dft_mintable",
    "dft_burnable_mintable",
    "dft_standard",
    "dft_types",
    "dft_utils",
    "dft_tx_storage"
]

[profile.release]
lto = true
opt-level = "z"
