name: Integration Test

on:
  workflow_call:
    inputs:
      features:
        required: true
        type: string

jobs:
  it:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          feature: ${{ fromJson(inputs.features) }}
    container:
      image: docker.io/kentsday/dfx_rust:bullseye-dfx-0.10.0-1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "src/package-lock.json"
      - uses: actions/download-artifact@v3
        with:
          name: dev
          path: ~/download/dev
      - name: run integration test
        run: |
          cd $GITHUB_WORKSPACE/src
          echo "scripts/features/**/${{ matrix.feature }}.feature" > feature_target.txt
          cp -rf ~/download/dev/* .
          dfx start --background
          ./sh_setup_dev.sh
          npm run test-report
          dfx stop
      - uses: deblockt/cucumber-report-annotations-action@v1.8
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"